type: http
name: List application documents
url: '{{baseUrl}}/applications/:applicationId/documents'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          [
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "1999-07-18T05:31:44.438Z",
              "verificationStatus": "pending"
            },
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "1991-04-06T05:20:29.023Z",
              "verificationStatus": "rejected"
            }
          ]
      headers:
        - key: Content-Type
          value: application/json
    name: List of documents
