type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 8186.807314694198,
            "termMonths": 7020,
            "status": "denied",
            "createdAt": "2006-06-28T23:46:45.947Z",
            "updatedAt": "1961-01-06T00:33:26.678Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "failed",
              "decision": "approved",
              "riskScore": 78,
              "evaluatedAt": "2009-09-26T15:30:55.764Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
